apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-sad
  labels:
    app: phpmyadmin-sad
    heritage: harpoon
    name: phpmyadmin-sad
    vender: qinguanos.io
spec:
  type: NodePort
  ports:
  - name: phpmyadminwui
    nodePort: 32123
    port: 80
    protocol: TCP
  selector:
    name: phpmyadmin-sad
